name: Weekly Update

on:
  schedule:
    - cron: '0 0 * * MON' # Run every Monday at midnight
  workflow_dispatch: # Allow manual trigger

env:
  EPMC_QUERY_KEYWORDS: '((TITLE:((visualization OR "visual analytics" OR dashboard) AND (healthcare OR health OR clinical))) OR (ABSTRACT:((visualization OR "visual analytics" OR dashboard) AND (healthcare OR health OR clinical))) OR (KW:((visualization OR "visual analytics" OR dashboard) AND (healthcare OR health OR clinical)))) AND HAS_ABSTRACT:y'
  EPMC_TARGET_KEYWORDS: '["visual analytics", "visualization", "dashboard", "visual", "artificial intelligence", "machine learning", "clinical decision support", "data", "informatics", "electronic health record"]'
  EPMC_KEYWORD_WEIGHTS: '{"visual analytics": 4, "visualization": 3, "dashboard": 3, "visual": 2, "artificial intelligence": 2, "machine learning": 2, "clinical decision support": 2, "data": 1, "informatics": 2, "electronic health record": 3}'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weekly update
        run: |
          # Create necessary directories
          mkdir -p data/raw data/weekly_reports docs

          # Run the pipeline
          python scripts/fetch_data.py --days_back 7

          # Get the date range for file naming
          START_DATE=$(date -d "7 days ago" +%Y-%m-%d)
          END_DATE=$(date +%Y-%m-%d)

          # Process the new data
          python scripts/parse_data.py \
            --input_file "data/raw/epmc_${START_DATE}_to_${END_DATE}.json" \
            --output_file "data/weekly_reports/epmc_${START_DATE}_to_${END_DATE}.csv"

          # Generate HTML
          python scripts/generate_html.py \
            --input_csv "data/weekly_reports/epmc_${START_DATE}_to_${END_DATE}.csv" \
            --output_html "docs/epmc_${START_DATE}_to_${END_DATE}.html"

          # Update directory index
          python scripts/generate_directory.py \
            --input_dir docs/ \
            --output_html docs/index.html \

      - name: Commit changes to main branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/raw/*.json data/weekly_reports/*.csv docs/*.html docs/index.html docs/styles.css docs/script.js
          git commit -m "Weekly Update: $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
